import { ambry, eko, jpmc, fitpage, basix, hdfc, zest } from "./contents";

export const caseStudies: any = {
  ambry: {
    caseStudyName: ambry.caseStudyName,
    heroSection: ambry.heroSection,
    overview: ambry.overview,
    objectiveDetails: ambry.objectiveDetails,
    challenges: ambry.challenges,
    solutions: ambry.solutions,
    otherWork: ambry.otherWork,
    typography: ambry.typography,
    visualDesign: ambry.visualDesigns,
    outcome: ambry.outcome,
  },
  eko: {
    caseStudyName: eko.caseStudyName,
    heroSection: eko.heroSection,
    overview: eko.overview,
    objectiveDetails: eko.objectiveDetails,
    challenges: eko.challenges,
    solutions: eko.solutions,
    otherWork: eko.otherWork,
    typography: eko.typography,
    visualDesign: eko.visualDesigns,
    outcome: eko.outcome,
  },
  jpmc: {
    caseStudyName: jpmc.caseStudyName,
    heroSection: jpmc.heroSection,
    overview: jpmc.overview,
    objectiveDetails: jpmc.objectiveDetails,
    challenges: jpmc.challenges,
    solutions: jpmc.solutions,
    otherWork: jpmc.otherWork,
    typography: jpmc.typography,
    visualDesign: jpmc.visualDesigns,
    wireFrames: jpmc.wireFrames,
    outcome: jpmc.outcome,
  },
  fitpage: {
    caseStudyName: fitpage.caseStudyName,
    heroSection: fitpage.heroSection,
    overview: fitpage.overview,
    objectiveDetails: fitpage.objectiveDetails,
    challenges: fitpage.challenges,
    solutions: fitpage.solutions,
    otherWork: fitpage.otherWork,
    typography: fitpage.typography,
    visualDesign: fitpage.visualDesigns,
    wireFrames: fitpage.wireFrames,
    outcome: fitpage.outcome,
  },
  basix: {
    caseStudyName: basix.caseStudyName,
    heroSection: basix.heroSection,
    overview: basix.overview,
    objectiveDetails: basix.objectiveDetails,
    challenges: basix.challenges,
    solutions: basix.solutions,
    otherWork: basix.otherWork,
    typography: basix.typography,
    visualDesign: basix.visualDesigns,
    outcome: basix.outcome,
  },
  hdfc: {
    caseStudyName: hdfc.caseStudyName,
    heroSection: hdfc.heroSection,
    overview: hdfc.overview,
    objectiveDetails: hdfc.objectiveDetails,
    challenges: hdfc.challenges,
    solutions: hdfc.solutions,
    otherWork: hdfc.otherWork,
    typography: hdfc.typography,
    visualDesign: hdfc.visualDesigns,
    wireFrames: hdfc.wireFrames,
    outcome: hdfc.outcome,
  },
  zest: {
    caseStudyName: zest.caseStudyName,
    heroSection: zest.heroSection,
    overview: zest.overview,
    objectiveDetails: zest.objectiveDetails,
    challenges: zest.challenges,
    solutions: zest.solutions,
    otherWork: zest.otherWork,
    typography: zest.typography,
    visualDesign: zest.visualDesigns,
    wireFrames: zest.wireFrames,
    outcome: zest.outcome,
  },
};
